name: ci-build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: 0 5 * * 2,5

env:
  CARGO_TERM_COLOR: always

jobs:
  clap_stdin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: lint
      run: make lint
    - name: build (lib)
      run: cargo build --verbose
    - name: test
      env:
        RUST_LOG: info
      run: make test
    - name: document
      run: make doc
